---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: /
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "flock.email"
keywords:    "flock, email, communication, one-to-many conversations, polls, questions and scheduling,  "
description: "Making communication with a group of people a pleasure"
source_link: ""
baseurl: "/flock-landingpage-2"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-71534751-1"
color: '#111111'


### template colors, used site-wide via css ###
colors:
  font_color: '#111111'
  black:     '#111111'
  white:     '#f8f8f8'
  grey:     '#CACACA'
  intro:      '#5A67FF'
  what:     '#6DE8CD'
  why:    '#C7FF85'
  features:    '#E8C36D'
  signup: '#FF5D46'
